apiVersion: v1
entries:
  Grafana:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2021-08-26T10:16:14.7789333+05:30"
    description: A Helm chart to setup Grafana tool
    digest: 007da35406ee38e4f507151d52adfcfb65f7bc8a89ca1c3a4e94ccfd4613d341
    name: Grafana
    type: application
    urls:
    - Grafana-0.1.0.tgz
    version: 0.1.0
generated: "2021-08-26T10:16:14.7736956+05:30"
